version: '2'

services:
  postal-app:
    container_name: postal-app
    image: tiredofit/postal
    ports:
      - 25:2525
    volumes:
      - ./data/postal:/opt/postal/config
    environment: 
      - VIRTUAL_HOST=postal.example.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=postal.example.com
      - LETSENCRYPT_EMAIL=email@example.com

      - ZABBIX_HOSTNAME=postal-app

      - DB_HOST=postal-db
      - DB_PORT=3306
      - DB_NAME=postal
      - DB_USER=postal
      - DB_PASS=postalpass
     ## A great idea is to delete this block after first install.
      - DB_ROOT_PASS=rootpassword
      - ADMIN_EMAIL=example@hostname.com
      - ADMIN_PASS=password
      - ADMIN_FNAME=Example
      - ADMIN_LNAME=Admin
     ##

      - RABBITMQ_HOST=postal-rabbitmq
      - RABBITMQ_USER=postal
      - RABBITMQ_PASS=password
      - RABBITMQ_VHOST=/postal

      - ENABLE_SPAMASSASSIN=false
      - ENABLE_CLAMAV=false
      - CLAMAV_HOST=postal-clamav
      - SPAMASSASSIN_HOST=postal-spamassassin
      
    restart: always
    networks:
      - proxy-tier

  postal-db:
    container_name: postal-db
    image: tiredofit/mariadb
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=postal
      - MYSQL_USER=postal
      - MYSQL_PASSWORD=postalpass
      - ZABBIX_HOSTNAME=postal-db
    networks:
      - proxy-tier

  postal-db-backup:
    container_name: postal-db-backup
    image: tiredofit/db-backup
    links:
     - postal-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - ZABBIX_HOSTNAME=postal-db-backup
      - DB_HOST=postal-db
      - DB_TYPE=mariadb
      - DB_NAME=postal
      - DB_USER=postal
      - DB_PASS=postalpass
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    networks:
      - proxy-tier
    restart: always

  postal-rabbitmq:
    container_name: postal-rabbitmq
    image: tiredofit/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=postal
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=/postal
      - ZABBIX_HOSTNAME=postal-rabbitmq
    networks:
      - proxy-tier
    restart: always

  postal-clamav:
    container_name: postal-clamav
    image: tiredofit/clamav
    volumes:
    - ./data/clamav:/data
    - ./logs/clamav:/var/log/clamav
    environment:
    - ZABBIX_HOSTNAME=postal-clamav
    networks:
      - proxy-tier
    restart: always

  postal-spamassassin:
    image: tiredofit/spamassassin
    container_name: postal-spamassassin-app
    volumes:
    - ./logs/spamassassin:/var/log/spamassassin
    - ./data/spamassassin/conf:/etc/mail/spamassassin
    - ./data/spamassassin/data:/var/lib/spamassassin
    environment:
    - ZABBIX_HOSTNAME=postal-spamassassin
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy

